common: &default
  app_name: Singulus
  distributed_tracing:
    enabled: true
  log_level: info

development:
  <<: *default
  app_name: Singulus (Development)

test:
  <<: *default
  monitor_mode: false

production:
  <<: *default
